// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'my-btn': string;
  'primary': string;
  'success': string;
}
declare var cssExports: CssExports;
export = cssExports;
