// 区域图
let areaData = [10, 30, 25, 12, 43, 25, 18, 12]
      let AreaChart_Width = 400
      let AreaChart_Height = 400
      let AreaChart_Svg = d3.select('body')
        .append('svg')
        .attr('width', AreaChart_Width)
        .attr('height', AreaChart_Height)
      let AreaChart_xScale = d3.scaleBand().domain(['1月', '2月', '3月', '4月', '5月', '6月']).range([0, AreaChart_Width - margin.left - margin.right])
      let AreaChart_yScale = d3.scaleLinear().domain([d3.min(areaData), d3.max(areaData)]).range([AreaChart_Height - margin.bottom - margin.top, 0])
      let AreaChart_xAxis = d3.axisBottom().scale(AreaChart_xScale)
      let AreaChart_yAxis = d3.axisLeft().scale(AreaChart_yScale)
      AreaChart_Svg.append('g')
        .attr('transform', 'translate(' + margin.left + ',' + (AreaChart_Height - margin.bottom) + ')')
        .call(AreaChart_xAxis)
      AreaChart_Svg.append('g')
        .attr('transform', 'translate(' + margin.left + ',' + margin.top + ')')
        .call(AreaChart_yAxis)
 
      // 颜色渐变
      let defs = AreaChart_Svg.append('defs')
      let linearGradient = defs.append('linearGradient')
        .attr('id', 'linearColor')
        .attr('x1', '0%')
        .attr('y1', '0%')
        .attr('x2', '0%')
        .attr('y2', '0%')
        .attr('y2', '100%')
      let a = d3.rgb(235, 0, 233)
      let b = d3.rgb(133, 0, 187)
      linearGradient.append('stop')
        .attr('offset', '0%')
        .style('stop-color', 'white')
        .transition().duration(2000)
        .style('stop-color', a.toString())
      linearGradient.append('stop')
        .style('stop-color', 'white')
        .transition().duration(2000)
        .attr('offset', '100%')
        .style('stop-color', b.toString())

      let area = d3.area()
        .x((d, i)=>margin.left + (AreaChart_Width - margin.left - margin.right) / lineData.length * (i + 0.5))
        .y((d, i)=>AreaChart_Height - margin.bottom)
        .y1((d, i)=>AreaChart_yScale(d))
        .curve(d3.curveBasis)

      AreaChart_Svg.append('path')
        .attr('d', area(areaData))
        .style('fill', 'url(#' + linearGradient.attr('id') + ')')