// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'index-app': string;
  'index-app-button': string;
  'index-app-logo': string;
  'index-app-title': string;
}
declare var cssExports: CssExports;
export = cssExports;
